server:
  port: 8085
  origin: ${ORIGIN:*}
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: master
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/game-events}
  sleuth:
    sampler:
      percentage: 1.0
